overview.html: overview.md
	markdown_py overview.md > overview.html

overview_pres.html: overview.md
	landslide overview.md -c -r -d overview_pres.html

web: overview.html
	open overview.html
pres: overview_pres.html
	open overview_pres.html